### ISSUE TITLE
How usable is this library ?

### ISSUE THREAD

**Issue by gbip** [kellerkindt/w5500#1]
Hello there !
I am planning to use this crate for a robotic project. We plan to use UDP to communicate between electronic boards.
Is there any bug that we should be aware of ? Is there any contribution that we could do ?
Thanks !

**Comment by kellerkindt** [comment]
I am using the library since march to record weather data and temperatures in my home (see https://home.watzko.de/).
The 'sample' project can be seen here: https://github.com/kellerkindt/bluepill_sensor

Its pretty reliable, no sudden crashes or the like. Runs, measures and answers on requests.
But there is no support beyond sending and receiving simple UDP packets.

**Comment by kellerkindt** [comment]
Thats what I am expecting (from the w5500 datasheet), and I have never experienced something else. Would be concerning otherwise. Feel free to open a bug report if you observed such a case.
